# ---------------------------------------------------------------- 统一维度

# category的 id
DIMS_ID = [
    "manufacturing",
    "government_governance",
    "healthcare",
    "energy_power",
    "finance",
    "transportation_logistics",
    "culture_tourism",
    "legal_services",
    "cross_border",
    "retail_ecommerce",
    "ai_service",
    "information_communication",
    "education",
    "scientific_research",
    "real_estate",
    "automobile",
    "hospitality",
    "construction",
    "mining",
    "agriculture",
    "leasing_business",
    "resident_services",
    "credit_service",
    "eco_environment",
    "statistics",
    "meteorology",
    "others",
    "emergency_safety",
    "media_marketing",
    "geospatial",
    "all_scenarios",
    "tobacco",
    "intellectual_property",
    "ceramics",
    "international_organization",
]

# product 表 tags 字段的取值来源 —— tags 存的是归并后的 35 个维度名，
DIMS_NAME = {
    "manufacturing": "制造业与工业",
    "government_governance": "政务与城市治理",
    "healthcare": "医疗健康",
    "energy_power": "能源电力",
    "finance": "金融业",
    "transportation_logistics": "交通运输、仓储与物流",
    "culture_tourism": "文化旅游与文体娱乐",
    "legal_services": "司法与法律服务",
    "cross_border": "跨境与外贸",
    "retail_ecommerce": "批发零售与电子商务",
    "ai_service": "人工智能与智能服务",
    "information_communication": "信息传输、软件与通信",
    "education": "教育",
    "scientific_research": "科学研究与技术服务业",
    "real_estate": "房地产业",
    "automobile": "汽车",
    "hospitality": "住宿和餐饮业",
    "construction": "建筑业",
    "mining": "采矿业",
    "agriculture": "农林牧渔",
    "leasing_business": "租赁和商务服务业",
    "resident_services": "居民服务与生活服务业",
    "credit_service": "信用服务",
    "eco_environment": "生态环保与绿色低碳",
    "statistics": "统计与社会统计",
    "meteorology": "气象服务",
    "others": "其他与综合",
    "emergency_safety": "应急管理与公共安全",
    "media_marketing": "新闻传媒与市场营销",
    "geospatial": "地理空间与遥感",
    "all_scenarios": "全场景/不限",
    "tobacco": "烟草",
    "intellectual_property": "知识产权",
    "ceramics": "陶瓷",
    "international_organization": "国际组织",
}